### ISSUE TITLE
can you please update build.gradle for 0.4.1

### ISSUE THREAD

**Issue by leela52452** [csicar/MensaPlan#9]
can you please update your build.gradle for [0.4.1 tag](https://github.com/csicar/MensaPlan/releases/tag/v0.4.1) 

thank you

**Comment by csicar** [comment]
done in eccec0af4334b81a49c97000b321446db0f2d047

Do you also need the tag moved or a new apk?

**Comment by leela52452** [comment]
i have raised an [issue](https://gitlab.com/fdroid/fdroiddata/issues/1811) and this is how, they responded `Update versionCode/Name too: https://github.com/csicar/MensaPlan/blob/master/app/build.gradle then delete the tag, then retag on the new commit`

i am not dev, so please excuse. i hope the above info will provide clarification.

**Comment by csicar** [comment]
Yes, thank you for opening the issue. The problem should be fixed now
